[package]
name = "inuti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nrf24l01 = "0.3.0"

[patch.crates-io]
nrf24l01 = { git = 'https://github.com/blennster/rust-nrf24l01' }