on:
  push:
    # paths:
    #   - 'src/**.rs'
    #   - 'Cargo.*'

name: build

jobs:
  rust:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install latest stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory
      - name: Add cross
        run: wget -qO - https://github.com/cross-rs/cross/releases/latest/download/cross-x86_64-unknown-linux-gnu.tar.gz | tar -xzf - -C ~/.cargo/bin

      - name: Run cross clippy
        run: cross clippy

      # This will use the default config in Cargo.toml
      - name: Run cross build
        run: cross build --release --target armv7-unknown-linux-gnueabihf
      
      - name: Upload build result
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: inuti
          path: target/armv7-unknown-linux-gnueabihf/release/inuti
