on:
  push:
    paths:
      - 'src/**.rs'
      - 'Cargo.*'

name: build

jobs:
  rust:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          default: true
          components: clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

      - name: Run cross clippy
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: clippy

      # This will use the default config in Cargo.toml
      - name: Run cross build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build 
          args: --release --target armv7-unknown-linux-gnueabihf
      
      - name: Publish build result
        uses: softprops/action-gh-release@v1
        with:
          files: target/armv7-unknown-linux-gnueabihf/inuti
